version: '2'
services:
    keralareliefcamps-app:
        image: keralareliefcamps
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://keralareliefcamps-mysql:3306/keralareliefcamps?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=keralareliefcamps-elasticsearch:9300
        ports:
            - 8080:8080
    keralareliefcamps-mysql:
        extends:
            file: mysql.yml
            service: keralareliefcamps-mysql
    keralareliefcamps-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: keralareliefcamps-elasticsearch
